# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Helper-Doc
version:      0.04
version_from: lib/Catalyst/Helper/Doc.pm
installdirs:  site
requires:
    Catalyst:                      5.3
    Pod::ProjectDocs:              0.22

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.29
